language: android
jdk: oraclejdk8

sudo: false

android:
  components:
    - build-tools-28.0.3
    - android-28

    - extra-android-m2repository
    - extra-android-support


before_script:
  - chmod +x gradlew

script:
  - ./gradlew assembleRelease
